### ISSUE TITLE
Exceptions when emoji-java is on the same classpath

### ISSUE THREAD

**Issue by donnerpeter** [felldo/JEmoji#8]
### JEmoji version

1.3.0

### Steps to reproduce

Have emoji-java and jemoji dependencies in the same project, in this order. 

### What is expected?

Both libraries can be used.

### What is actually happening?

`net.fellbaum.jemoji.EmojiManager`'s static initializer fails with an exception:

Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `net.fellbaum.jemoji.Emoji`, problem: Cannot invoke "java.util.Collection.iterator()" because "c" is null
 at [Source: (StringReader); line: 13, column: 3] (through reference chain: java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:2052)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:587)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:610)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:293)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:288)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:519)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3660)
	at net.fellbaum.jemoji.EmojiManager.<clinit>(EmojiManager.java:38)

### Any additional comments?

This seems to be caused by both libraries using the same `emojis.json` at the same relative path, which the single classloader cannot differentiate. So a possible fix would be to place the jemoji json to another, more unique location. I can prepare a PR if needed.

**Comment by felldo** [comment]
When I tried to reproduce this issue, I got the exact opposite problem: `emoji-java` cannot be initialized, because it finds my `emojis.json` file.
What is the reason you are still using `emoji-java` if you plan on migrating? It's outdated and no longer maintianed for several years. So for now I don't see any reason why someone would want to have both dependencies if they are used for the exact same purpose

**Comment by donnerpeter** [comment]
The exact exception probably depends on the classpath order, but one of the libraries would probably fail to load.
Unfortunately, I'm also using a library that depends on `emoji-java` transitively, and I need to run both that library and `jemoji` in different scenarios.

**Comment by felldo** [comment]
I see and this is probably not the ideal situation if other libraries depend on `emoji-java`.
Therefore, I have changed the location of the file and a new version `1.3.1` has already been released (also includes the new emojis from september :) )

**Comment by donnerpeter** [comment]
Thank you so much!
