### ISSUE TITLE
ExceptionInInitializerError when calling EmojiManager.getAllEmojis()

### ISSUE THREAD

**Issue by jhakz** [felldo/JEmoji#9]
### JEmoji version

1.3.1

### Steps to reproduce

I just made a log to know the size of the list.

  Log.d("onClick: ", String.valueOf(EmojiManager.getAllEmojis().size()));

### What is expected?

That it works

### What is actually happening?

The specific error indicates that a java.lang.IllegalArgumentException is being thrown in the java.util.regex.Pattern class, and the cause is "UNICODE_CHARACTER_CLASS flag not supported".

This error usually occurs when using a regular expression that makes use of the Unicode character class (e.g., \p{...}) with a configuration that does not support this feature. from what I could understand.

### Any additional comments?

Sorry if my English is bad, I use translator, Thank you

**Comment by felldo** [comment]
Hi, can you please send the stacktrace you get?

**Comment by jhakz** [comment]
Hello, how are you?
This is the error that I get when I call this function from an onClick of a button:

private void getSizeEmojis() {
        Log.d("onClick: onCreate ", String.valueOf(EmojiManager.getAllEmojis().size()));
    }

Exception:

java.lang.ExceptionInInitializerError
                                                                                                    	at com.squash.text.processor.MainActivity.getSizeEmojis(MainActivity.java:59)
                                                                                                    	at com.squash.text.processor.MainActivity.access$000(MainActivity.java:16)
                                                                                                    	at com.squash.text.processor.MainActivity$1.onClick(MainActivity.java:37)
                                                                                                    	at android.view.View.performClick(View.java:7545)
                                                                                                    	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211)
                                                                                                    	at android.view.View.performClickInternal(View.java:7522)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:29566)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211)
                                                                                                    	at android.os.Looper.loop(Looper.java:300)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8272)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
                                                                                                    Caused by: java.lang.IllegalArgumentException: UNICODE_CHARACTER_CLASS flag not supported
                                                                                                    	at java.util.regex.Pattern.<init>(Pattern.java:1383)
                                                                                                    	at java.util.regex.Pattern.compile(Pattern.java:947)
                                                                                                    	at net.fellbaum.jemoji.EmojiManager.<clinit>(EmojiManager.java:49)
                                                                                                    	at com.squash.text.processor.MainActivity.getSizeEmojis(MainActivity.java:59) 
                                                                                                    	at com.squash.text.processor.MainActivity.access$000(MainActivity.java:16) 
                                                                                                    	at com.squash.text.processor.MainActivity$1.onClick(MainActivity.java:37) 
                                                                                                    	at android.view.View.performClick(View.java:7545) 
                                                                                                    	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211) 
                                                                                                    	at android.view.View.performClickInternal(View.java:7522) 
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0) 
                                                                                                    	at android.view.View$PerformClick.run(View.java:29566) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211) 
                                                                                                    	at android.os.Looper.loop(Looper.java:300) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8272) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by felldo** [comment]
Can you tell me a bit more about your environment? What Java version do you use? Do you develop something for android?
